apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}