apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://homarr-labs.github.io/charts/
      chart: homarr
      targetRevision: 7.2.0
      helm:
        valueFiles:
          - $values/kubernetes/helm-charts/homarr/values.yaml
      
    - repoURL: https://github.com/x64nik/homelab.git
      targetRevision: main
      ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true