replicaCount: 1

image:
  repository: docker.io/jellyfin/jellyfin
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: "jellyfin"
fullnameOverride: "jellyfin"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "jellyfin-svc-account"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# -- Security context for the container.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Define a custom runtimeClassName for the pod.
runtimeClassName: ''

# -- Define a priorityClassName for the pod.
priorityClassName: ""

# -- Deployment strategy configuration. See `kubectl explain deployment.spec.strategy`.
deploymentStrategy:
  type: RollingUpdate

# -- Annotations to add to the deployment.
deploymentAnnotations: {}

service:
  type: ClusterIP
  port: 8096
  annotations: {}
  labels: {}

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: jellyfin-lab.configcloud.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resource requests and limits for the Jellyfin container.
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Configure liveness probe for Jellyfin.
livenessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
  # successThreshold: 1
  # failureThreshold: 3
  # timeoutSeconds: 1
  # periodSeconds: 10

# -- Configure readiness probe for Jellyfin.
readinessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
  # successThreshold: 1
  # failureThreshold: 3
  # timeoutSeconds: 1
  # periodSeconds: 10

# -- Additional volumes to mount in the Jellyfin pod.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volume mounts for the Jellyfin container.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# -- Node selector for pod scheduling.
nodeSelector: {}

# -- Tolerations for pod scheduling.
tolerations: []

# -- Affinity rules for pod scheduling.
affinity: {}

jellyfin:
  # -- Enable DLNA. Requires host network. See: https://jellyfin.org/docs/general/networking/dlna.html
  enableDLNA: false
  # -- Custom command to use as container entrypoint.
  command: []
  # -- Additional arguments for the entrypoint command.
  args: []
  # -- Additional environment variables for the container.
  env: []

persistence:
  config:
    # -- set to false to use emptyDir
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    # -- Custom annotations to be added to the PVC
    annotations: {}
    # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: 'nfs-csi'
    ## -- Use an existing PVC for this mount
    # existingClaim: ''
  media:
    # -- set to false to use emptyDir
    enabled: true
    # -- Type of volume for media storage (pvc, hostPath, emptyDir). If 'enabled' is false, 'emptyDir' is used regardless of this setting.
    type: pvc
    # -- Path on the host node for media storage, only used if type is 'hostPath'.
    hostPath: ""
    # -- PVC specific settings, only used if type is 'pvc'.
    accessMode: ReadWriteOnce
    size: 25Gi
    # -- Custom annotations to be added to the PVC
    annotations: {}
    # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: 'nfs-csi'
    ## -- Use an existing PVC for this mount
    # existingClaim: ''

# -- Configuration for metrics collection and monitoring
metrics:
  # -- Enable or disable metrics collection
  enabled: false
  # -- Configuration for the Prometheus ServiceMonitor
  serviceMonitor:
    # -- Enable or disable the creation of a ServiceMonitor resource
    enabled: false
    # -- Namespace where the ServiceMonitor resource should be created. Defaults to Release.Namespace
    namespace: ''
    # -- Labels to add to the ServiceMonitor resource
    labels: {}
    # -- Interval at which metrics should be scraped
    interval: 30s
    # -- Timeout for scraping metrics
    scrapeTimeout: 30s
    # -- Path to scrape for metrics
    path: /metrics
    # -- Port to scrape for metrics
    port: 8096
    # -- Scheme to use for scraping metrics (http or https)
    scheme: http
    # -- TLS configuration for scraping metrics
    tlsConfig: {}
    # -- Relabeling rules for the scraped metrics
    relabelings: []
    # -- Relabeling rules for the metrics before ingestion
    metricRelabelings: []
    # -- Target labels to add to the scraped metrics
    targetLabels: []

# -- additional init containers to run inside the pod.
extraInitContainers: []
  
# -- additional sidecar containers to run inside the pod.
extraContainers: []