version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: cc-db-dev-postgres
    environment:
      POSTGRES_USER: nik
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cc-db-dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@configcloud.net
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    restart: always
volumes:
  pgdata:
