apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://qdrant.github.io/qdrant-helm/
      chart: qdrant
      targetRevision: 1.17.0
      helm:
        valueFiles:
          - $values/kubernetes/helm-charts/qdrant/values.yaml
    
    - repoURL: https://github.com/x64nik/homelab.git
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true