services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin 
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - media-server-data:/media
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  media-server-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/media-server-data