apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb-prometheus-servicemonitor
  namespace: monitoring
  labels:
    name: metallb-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: metallb-speaker
  namespaceSelector:
    matchNames:
    - metallb-system
  endpoints:
  - port: 7473