apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 7.4.12
      helm:
        values: |
          apiService:
            create: true
            # Annotations to add to the API service
            annotations: {}
            # Specifies whether to skip TLS verification
            insecureSkipTLSVerify: true
            # The PEM encoded CA bundle for TLS verification
            caBundle: ""

          defaultArgs:
            - --cert-dir=/tmp
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --kubelet-use-node-status-port
            - --metric-resolution=15s

          metrics:
            enabled: false

          # See https://github.com/kubernetes-sigs/metrics-server#scaling
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
              # limits:
              #   cpu:
              #   memory:
      
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true