apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- if and .Values.config.data  }}
  {{- $localConfig := default dict .Values.config.data }}
  {{- range $key, $value := $localConfig }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}