apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.27.1
      chart: cloudnative-pg
      helm:
        valueFiles:
          - $values/kubernetes/helm-charts/cnpg-operator/values/default.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
