{
 "title": "K8s logs via VictoriaLogs",
 "tags": [ "demo" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "ds",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "query": { "query": "" } },
   {
    "name": "pod",
    "query": {
     "query": "kubernetes.pod_namespace: in($namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "kubernetes.pod_namespace: in($namespace) and kubernetes.pod_name: in($pod)"
    }
   },
   { "name": "filter", "query": "*" },
   { "name": "limit", "query": "100, 500, 1000, 2000" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Stats ($namespace:$pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) | stats by(kubernetes.pod_namespace) count() \n| stats count()"
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod)\n| stats by(kubernetes.pod_name) count() \n| count()"
    }
   ]
  },
  {
   "title": "Total logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| stats count() "
    }
   ]
  },
  {
   "title": "Logs by log.level by last 24h",
   "type": "gauge",
   "description": "Here, _time: $__range  needs to be removed later, once ??gh_issue?? is implemented",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| format if (log.level:\"\") \"other\" as log.level\n| stats by (log.level) count() \n| sort desc",
     "legendFormat": "{{log.level}}"
    }
   ]
  },
  {
   "title": "Logs by namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| format if (kubernetes.pod_namespace:\"\") \"unknown\" as kubernetes.pod_namespace\n| stats by (kubernetes.pod_namespace) count() total\n| sort by(total) desc \n| limit 5",
     "legendFormat": "{{kubernetes.pod_namespace}}"
    }
   ]
  },
  {
   "title": "Logs by log.level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| format if (log.level:\"\") \"other\" as log.level\n| stats by (log.level) count() total\n| sort by(total) desc ",
     "legendFormat": "{{log.level}}"
    }
   ]
  },
  {
   "title": "Stats by pod ($namespace:$pod:$filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Top field-value pairs (facets)",
   "type": "table",
   "description": "Shows the most common field-value pairs \n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#facets-pipe",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| $filter\n| facets 3\n| sort by(hits) desc"
    }
   ]
  },
  {
   "title": "Top 10 log patterns (collapse_nums)",
   "type": "table",
   "description": "Shows most common log patterns on the time range\n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| $filter\n| collapse_nums prettify\n| top 10 by(_msg)"
    }
   ]
  },
  {
   "title": "Logs rate ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| $filter\n| stats by (kubernetes.pod_name,kubernetes.container_name) rate() logs_rate\n| filter logs_rate: > 0",
     "legendFormat": "{{kubernetes.pod_name}} ({{kubernetes.container_name}})"
    }
   ]
  },
  {
   "title": "Logs total ($pod)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| $filter\n| stats by (kubernetes.pod_name,kubernetes.container_name) count() logs_total",
     "legendFormat": "{{kubernetes.pod_name}} ({{kubernetes.container_name}})"
    }
   ]
  },
  { "title": "Raw logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "pod logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "repeat": "limit",
   "targets": [
    {
     "expr": "kubernetes.pod_namespace:in($namespace) kubernetes.pod_name:in($pod) kubernetes.container_name:in($container)\n| $filter\n| sort by (_time)\n| limit $limit"
    }
   ]
  }
 ]
}