apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
spec:
  selector:
    prometheus: prometheus-persistant
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: web
  # loadBalancerIP: 192.168.0.150