apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: home-pool
  namespace: kube-system
spec:
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  blocks:
    - start: "192.168.0.30"
      stop: "192.168.0.35"