apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  # loadBalancerIP: 192.168.0.150