apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi